import { FEEDBACK_PROMPT } from "@/services/Constants";

export async function POST(req) {
    const {conversation} = await req.json();
    const FINAL_PROMPT = FEEDBACK_PROMPT.replace('{{conversation}}',JSON.stringify(conversation));
    
    try {
        const openai = new OpenAI({
          baseURL: "https://openrouter.ai/api/v1",
          apiKey: process.env.OPENROUTER_API_KEY,
        });
    
        const completion = await openai.chat.completions.create({
          model: "openai/gpt-3.5-turbo",
          messages: [
            { role: "user", content: FINAL_PROMPT }
          ],
        });
    
        console.log("Full OpenAI response:", completion);
    
        if (completion?.choices && completion.choices.length > 0) {
          console.log(completion.choices[0].message);
          return NextResponse.json(completion.choices[0].message);
        } else {
          console.error("No choices returned by OpenAI:", completion);
          return NextResponse.json({ error: "No response generated by AI model." }, { status: 500 });
        }
      } catch (e) {
        console.error("OpenAI Error:", e);
        return NextResponse.json({ error: "AI request failed", details: e.message || e }, { status: 500 });
      }

}